/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio5;

import hola.mundo.Calculadora;
import java.awt.Color;
import static java.awt.Color.blue;
import static java.awt.Color.red;
import javax.swing.JOptionPane;

/**
 *
 * @author AXO<l211080078@iztapalapa.tecnm.mx>
 */
public class SplashAXO extends javax.swing.JFrame {

    /**
     * Creates new form SplashAXO
     */
    public SplashAXO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCargando = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();
        lblValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCargando.setForeground(new java.awt.Color(255, 0, 51));
        lblCargando.setText("Cargando...");
        jPanel1.add(lblCargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        barra.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 500, 10));

        lblValor.setForeground(new java.awt.Color(255, 51, 51));
        lblValor.setText("0%");
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       SplashAXO sp= new SplashAXO();
       sp.setVisible(true);
       Calculadora cal= new Calculadora();
        sp.barra.setForeground(blue);//CAMBIAR EL COLOR DE LA BARRA
        try {
            for(int i=0;i<=100;i++){
                Thread.sleep(100);//TEMPORIZADOR
                sp.lblValor.setText(i+"%");
                if(i==10){
                    sp.lblCargando.setText("Conectando...");
                }
                if(i==30){
                    sp.lblCargando.setText("Iniciando sesion...");
                }
                if(i==50){
                    sp.lblCargando.setText("Validando datos...");
                }
                if(i==70){
                    sp.lblCargando.setText("Conectando a la base de datos...");
                }
                if(i==90){
                    sp.lblCargando.setText("Conexion exitosa");
                }
                if(i==100){
                    sp.lblCargando.setText("Iniciando calculadora...");
                    cal.setVisible(true);
                    System.out.println("Muestra Calculadora");
                }
                sp.barra.setValue(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        sp.dispose();//CIERRA EL FRONT 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargando;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
