
package Views;

import Models.Itiz;
import java.util.ArrayList;


public class JDocentes extends javax.swing.JInternalFrame {


    public JDocentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        /*
        if(Mensaje("Escribe el No.Control",this.jTextFieldNoControl)) return;
        if(Mensaje("Escribe el Nombre",this.jTextFieldNombre)) return;
        if(Mensaje("Escribe el Correo",this.jTextFieldCorreo)) return;
        if(Mensaje("Escribe la direccion",this.jTextFieldDireccion)) return;
        if(Mensaje("Escribe el Semestre",this.jTextFieldSemestre)) return;
        if(Mensaje("Escribe el Telefono",this.jTextFieldTelefono)) return;

        Estudiantes = new Estudiantes(
            this.jTextFieldNoControl.getText(),
            this.jComboBoxCarrera.getModel().getSelectedItem().toString(),
            this.jTextFieldSemestre.getText()
        );
        Estudiantes.Correo = this.jTextFieldCorreo.getText();
        Estudiantes.Direccion = this.jTextFieldDireccion.getText();
        Estudiantes.Nombre = this.jTextFieldNombre.getText();
        Estudiantes.Telefono = this.jTextFieldTelefono.getText();

        ITIZ.add(Estudiantes);
        JOptionPane.showMessageDialog(this,
            "Informacion",
            "Datos Guardados",
            JOptionPane.INFORMATION_MESSAGE);

        */

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    public void setArrayList(ArrayList<Itiz> ITIZ){
        this.ITIZ = ITIZ;
    }
    
    ArrayList<Itiz> ITIZ;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    // End of variables declaration//GEN-END:variables
}
